export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_LOADING = 'GET_MESSAGES_LOADING';
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
